name: Snyk security scan
on: push
jobs:
  security:
    runs-on: ubuntu-latest    
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
      - uses: actions/checkout@master
          
      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        with:
          snyk-version: v1.1295.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      
      - name: Snyk Code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        #run: snyk code test --sarif-file-output=snyk-code.sarif
        run: snyk code test --severity-threshold=low --sarif-file-output=snyk-code.sarif
          
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif 
      
      # Push the Snyk Code results into GitHub Code Scanning tab
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif  
